import Footer from './Components/Footer'
import Header from './Components/Header'
import './globals.css'
import { Saira } from 'next/font/google'
/* import logo from '../src/logo1.png';
import styles from '../styles/page.module.css';
import Link from 'next/link'; */


//const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const font = Saira({
  weight: ['400', '700'],
  subsets: ['latin']
})

export async function getServerSideProps(context) {
  return {
    props: { message: `Next.js is awesome` }, // will be passed to the page component as props
  }
}

export default function RootLayout({ children }) {

  return (    
    <html lang="en">
      <body className={font.className}>
        <Header />
        {children}
        <Footer />
      </body>       
    </html>
  )
}
